Fix shape-rendering property
zpao/qrcode.react pull request #204
Opened 2022-06-21 12:56 UTC by DannyvanderJagt

The SVG property `shapeRendering` is placed at the wrong place(s). It is placed at `<svg/>` instead it should be placed at `<path....`

[SVG shape-rendering docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering)

2022-06-21 16:23 UTC, zpao requested changes
Good catch, thanks! I do wonder how much it matters here since I make the viewbox the exact size and only use whole units _but_ it certainly doesn't hurt. I obviously thought it was a good idea year ago :)

If you can fix lint then great, otherwise I'll apply that one fix and get this merged.

2022-06-21 19:45 UTC, DannyvanderJagt commented
Thanks! Not sure either, just found it during debugging. I fixed the linting 👍

2022-06-22 05:29 UTC, zpao approved these changes

2022-06-22 05:30 UTC, merged

2022-06-22 05:30 UTC, zpao commented
Thanks again! I'll ship this in the next version (soon!)